version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  news-parser:
    build:
      context: ./App/WebApp
      dockerfile: ./Dockerfile
    ports:      
      - "8091:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

volumes:
  postgres: